### ISSUE TITLE
Make it dynamic

### ISSUE THREAD

**Issue by Sin-Sumit** [Sin-Sumit/Accordion#1]
As you expand one question using +, and again if you expand the other question, you will notice that both will remain expanded until you collapse them.
So, try to add such functionality which works as follows:
- When a question is expanded, & when you try to expand another question, then the last question gets collapse or all the other collapse by themselves except the current one which is expanded.

**Comment by sanyagoyal2000** [comment]
Hi 
I would like to contribute to this issue

**Comment by Tejaswi-Chaudhari** [comment]
Hello @Sin-Sumit , I would like to try this
Could you assign this to me?

**Comment by muhammadsuheer** [comment]
@Sin-Sumit  Can you assign this to me sir

**Comment by Tejaswi-Chaudhari** [comment]
Hello @Sin-Sumit 
Please review PR #2

**Comment by oggy107** [comment]
I am unable to start the developement server. Please help
![Screenshot 2021-10-04 145359](https://user-images.githubusercontent.com/71421735/135827514-933e94d0-6eb5-43b4-823b-f1c941247fc3.png)

**Comment by Sin-Sumit** [comment]
First, install the node modules using npm install

Then run npm start

**Comment by oggy107** [comment]
it worked... ty sir

**Comment by Oggy107** [comment]
am i allowed to make changes to the data.js file?
